# Generated by Django 2.1.7 on 2019-03-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeConnectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=200)),
                ('last_online_timestr', models.DateTimeField(verbose_name='date published')),
                ('node_address', models.CharField(max_length=200)),
            ],
        ),
    ]
